const exactMessages: Record<string, string> = {
  "Route not found": "آدرس درخواست پیدا نشد.",
  "Validation failed": "اطلاعات واردشده معتبر نیست.",
  "Internal server error": "خطای داخلی رخ داد. لطفاً دوباره کوشش کنید.",
  "Authentication required": "برای انجام این کار باید وارد حساب شوید.",
  "Invalid or expired token": "نشست شما نامعتبر یا منقضی شده است. دوباره وارد شوید.",
  "Session is no longer active": "نشست شما دیگر فعال نیست. دوباره وارد شوید.",
  "User is disabled": "حساب کاربری شما غیرفعال است.",
  "Invalid username or password": "نام کاربری یا رمز عبور نادرست است.",
  "Logged out": "از حساب خارج شدید.",
  "Permission denied": "شما اجازه انجام این کار را ندارید.",
  "Access policy is not configured for this route": "دسترسی این بخش در سیستم تنظیم نشده است.",
  "Request failed": "درخواست انجام نشد. لطفاً دوباره کوشش کنید.",
  "Product not found": "محصول مورد نظر پیدا نشد.",
  "Sale not found": "فروش مورد نظر پیدا نشد.",
  "Purchase not found": "خرید مورد نظر پیدا نشد.",
  "Warehouse not found": "گدام مورد نظر پیدا نشد.",
  "Currency not found": "کرنسی مورد نظر پیدا نشد.",
  "Unit not found": "واحد مورد نظر پیدا نشد.",
  "Party not found": "طرف حساب مورد نظر پیدا نشد.",
  "Account not found": "حساب مورد نظر پیدا نشد.",
  "Customer not found": "مشتری مورد نظر پیدا نشد.",
  "Supplier not found": "فروشنده مورد نظر پیدا نشد.",
  "Employee not found": "کارمند مورد نظر پیدا نشد.",
  "Role not found": "نقش مورد نظر پیدا نشد.",
  "Device not found": "دستگاه مورد نظر پیدا نشد.",
  "Bank account not found": "حساب بانکی مورد نظر پیدا نشد.",
  "Cash register not found": "صندوق مورد نظر پیدا نشد.",
  "Payment account not found": "حساب پرداخت مورد نظر پیدا نشد.",
  "Receive account not found": "حساب دریافت مورد نظر پیدا نشد.",
  "Refund account not found": "حساب برگشت پول مورد نظر پیدا نشد.",
  "Payment transaction not found": "تراکنش پرداخت مورد نظر پیدا نشد.",
  "Money transfer not found": "انتقال پول مورد نظر پیدا نشد.",
  "Stock movement not found": "حرکت موجودی مورد نظر پیدا نشد.",
  "Inventory transfer not found": "انتقال موجودی مورد نظر پیدا نشد.",
  "Opening stock movement not found": "حرکت موجودی اولیه پیدا نشد.",
  "Held cart not found": "سبد معلق مورد نظر پیدا نشد.",
  "POS session not found": "نشست صندوق فروش پیدا نشد.",
  "Attendance period not found": "دوره حاضری پیدا نشد.",
  "Attendance record not found": "رکورد حاضری پیدا نشد.",
  "Payroll run not found": "دوره معاش مورد نظر پیدا نشد.",
  "Employee payment not found": "پرداخت معاش مورد نظر پیدا نشد.",
  "Journal entry not found": "سند حسابداری مورد نظر پیدا نشد.",
  "Financial category not found": "کتگوری مالی مورد نظر پیدا نشد.",
  "Currency rate not found": "نرخ کرنسی مورد نظر پیدا نشد.",
  "Attachment not found": "ضمیمه مورد نظر پیدا نشد.",
  "Attachment file not found": "فایل ضمیمه پیدا نشد.",
  "Thumbnail not found": "پیش‌نمایش فایل پیدا نشد.",
  "Invalid attachment path": "مسیر فایل ضمیمه معتبر نیست.",
  "Barcode is required": "بارکود ضروری است.",
  "text is required": "متن ضروری است.",
  "barcode or productId is required": "بارکود یا محصول ضروری است.",
  "currencyId is required": "کرنسی ضروری است.",
  "periodId is required": "دوره حاضری ضروری است.",
  "Party is required": "طرف حساب ضروری است.",
  "Invalid date": "تاریخ واردشده معتبر نیست.",
  "Invalid hire date": "تاریخ استخدام معتبر نیست.",
  "Invalid effectiveAt": "تاریخ و ساعت نرخ معتبر نیست.",
  "Invalid expiryDate": "تاریخ انقضا معتبر نیست.",
  "Invalid purchaseDate": "تاریخ خرید معتبر نیست.",
  "Invalid shift time": "زمان شیفت معتبر نیست.",
  "QR token is invalid or expired": "کد QR نامعتبر یا منقضی شده است.",
  "Today is not a workday": "امروز روز کاری نیست.",
  "This user is not linked to an active employee": "این کاربر به کارمند فعال متصل نیست.",
  "Username and password are required": "نام کاربری و رمز عبور ضروری است.",
  "Password is required for new users": "برای کاربر جدید رمز عبور ضروری است.",
  "Image file is required": "فایل عکس ضروری است.",
  "Only image files are allowed": "فقط فایل‌های عکس قابل قبول هستند.",
  "Backup permission is required": "اجازه دسترسی به بکاپ لازم است.",
  "Backup job not found": "کار بکاپ پیدا نشد.",
  "Backup job was not created": "کار بکاپ ساخته نشد.",
  "Invalid backup filename": "نام فایل بکاپ معتبر نیست.",
  "Backup file could not be read": "فایل بکاپ خوانده نشد.",
  "Backup validated": "بکاپ معتبر است.",
  "Backup validation failed": "اعتبارسنجی بکاپ ناکام شد.",
  "Backup restore failed": "بازگردانی بکاپ ناکام شد.",
  "Backup deleted": "بکاپ حذف شد.",
  "Backup restored and verified successfully. Sign in again to continue.": "بکاپ با موفقیت بازگردانی و بررسی شد. برای ادامه دوباره وارد شوید.",
  "Only AFN can be the base currency": "فقط افغانی می‌تواند کرنسی پایه باشد.",
  "AFN must remain the base currency": "افغانی باید کرنسی پایه باقی بماند.",
  "The base AFN currency code cannot be changed": "کد کرنسی پایه افغانی قابل تغییر نیست.",
  "Currency deactivated": "کرنسی غیرفعال شد.",
  "Warehouse deactivated": "گدام غیرفعال شد.",
  "Unit deactivated": "واحد غیرفعال شد.",
  "Party deactivated": "طرف حساب غیرفعال شد.",
  "Role disabled": "نقش کاربری غیرفعال شد.",
  "User disabled": "کاربر غیرفعال شد.",
  "Employee disabled": "کارمند غیرفعال شد.",
  "Cash register deactivated": "صندوق غیرفعال شد.",
  "Bank account deactivated": "حساب بانکی غیرفعال شد.",
  "Product deactivated": "محصول غیرفعال شد.",
  "Sale is already cancelled": "این فروش قبلاً ابطال شده است.",
  "Purchase is already cancelled": "این خرید قبلاً ابطال شده است.",
  "Sale return is already cancelled": "این برگشت فروش قبلاً ابطال شده است.",
  "Purchase return is already cancelled": "این برگشت خرید قبلاً ابطال شده است.",
  "Money transfer is already cancelled": "این انتقال پول قبلاً ابطال شده است.",
  "Transaction is already cancelled": "این تراکنش قبلاً ابطال شده است.",
  "Payment account is missing": "حساب پرداخت مشخص نشده است.",
  "Refund account is required": "حساب برگشت پول ضروری است.",
  "Receive account is required": "حساب دریافت ضروری است.",
  "Supplier is required for invoice payment": "برای پرداخت فاکتور، فروشنده ضروری است.",
  "Customer is required when return is not fully refunded": "برای برگشتی با مبلغ باقی‌مانده، مشتری ضروری است.",
  "Supplier is required when return is not fully received": "برای برگشتی با مبلغ باقی‌مانده، فروشنده ضروری است.",
  "Not enough cash balance": "موجودی صندوق کافی نیست.",
  "Not enough bank balance": "موجودی حساب بانکی کافی نیست.",
  "Not enough balance in account": "موجودی حساب کافی نیست.",
  "Not enough balance in source account": "موجودی حساب مبدا کافی نیست.",
  "Not enough balance in payment account": "موجودی حساب پرداخت کافی نیست.",
  "Not enough balance for refund": "موجودی حساب برای برگشت پول کافی نیست.",
  "Currency rate could not be resolved": "نرخ کرنسی برای این عملیات پیدا نشد.",
  "Cannot transfer to the same account": "انتقال پول به همان حساب مجاز نیست.",
  "Source and destination warehouses must be different": "گدام مبدا و مقصد باید متفاوت باشند.",
  "Transfer currency must be the same": "کرنسی انتقال باید یکسان باشد.",
  "Selected party is not a customer": "طرف حساب انتخاب‌شده مشتری نیست.",
  "Selected party is not a supplier": "طرف حساب انتخاب‌شده فروشنده نیست.",
  "Payment account currency must match selected currency": "کرنسی حساب پرداخت باید با کرنسی انتخاب‌شده یکسان باشد.",
  "Payment account currency must match purchase currency": "کرنسی حساب پرداخت باید با کرنسی خرید یکسان باشد.",
  "Refund account currency must match sale currency": "کرنسی حساب برگشت پول باید با کرنسی فروش یکسان باشد.",
  "Receive account currency must match purchase currency": "کرنسی حساب دریافت باید با کرنسی خرید یکسان باشد.",
  "Account currency must match entry currency": "کرنسی حساب باید با کرنسی سند یکسان باشد.",
  "Payment account currency mismatch": "کرنسی حساب پرداخت یکسان نیست.",
  "Only income and expense entries can be cancelled here": "فقط اسناد درآمد و مصرف از این بخش قابل ابطال هستند.",
  "This transaction cannot be cancelled directly": "این تراکنش مستقیم قابل ابطال نیست.",
  "System roles cannot be deleted": "نقش‌های سیستمی قابل حذف نیستند.",
  "One or more permissions were not found": "یک یا چند دسترسی پیدا نشد.",
  "Only Admin can review historical return quality": "فقط مدیر سیستم می‌تواند کیفیت برگشتی‌های قدیمی را بررسی کند.",
  "Only Admin can repair historical COGS": "فقط مدیر سیستم می‌تواند قیمت تمام‌شده فروش‌های قدیمی را اصلاح کند.",
  "Legacy management report is disabled": "گزارش مدیریتی قدیمی غیرفعال است."
};

const patterns: Array<[RegExp, string | ((match: RegExpMatchArray) => string)]> = [
  [/^Permission required: .+$/i, "شما اجازه لازم برای انجام این کار را ندارید."],
  [/^Server is in maintenance mode:.*$/i, "سرور در حالت نگهداری است. لطفاً چند لحظه بعد دوباره کوشش کنید."],
  [/^From date must be before to date$/i, "تاریخ شروع باید پیش از تاریخ پایان باشد."],
  [/^Expiry date is required for this product$/i, "برای این محصول تاریخ انقضا ضروری است."],
  [/^Selected unit is not configured for this product$/i, "واحد انتخاب‌شده برای این محصول تعریف نشده است."],
  [/^Product not found:.+$/i, "محصول مورد نظر پیدا نشد."],
  [/^Warehouse not found:.+$/i, "گدام مورد نظر پیدا نشد."],
  [/^Unit is not configured for product:.+$/i, "واحد انتخاب‌شده برای این محصول تعریف نشده است."],
  [/^Invalid expiryDate for product:.+$/i, "تاریخ انقضای محصول معتبر نیست."],
  [/^Sale item not found:.+$/i, "قلم فروش مورد نظر پیدا نشد."],
  [/^Purchase item not found:.+$/i, "قلم خرید مورد نظر پیدا نشد."],
  [/^Return quantity exceeds sold quantity for .+$/i, "مقدار برگشتی از مقدار فروخته‌شده بیشتر است."],
  [/^Return quantity exceeds purchased quantity for .+$/i, "مقدار برگشتی از مقدار خریداری‌شده بیشتر است."],
  [/^Not enough remaining stock to return .+$/i, "موجودی باقی‌مانده برای برگشت کافی نیست."],
  [/^Not enough stock for concurrent .+$/i, "موجودی به‌دلیل ثبت هم‌زمان کافی نیست. دوباره کوشش کنید."],
  [/^Not enough (cash|bank) balance to cancel .+$/i, "موجودی حساب برای ابطال این سند کافی نیست."],
  [/^Duplicate return item was provided$/i, "یک قلم برگشتی بیش از یک‌بار وارد شده است."],
  [/^Refund amount cannot exceed return total$/i, "مبلغ برگشت پول نمی‌تواند بیشتر از جمع برگشتی باشد."],
  [/^Received amount cannot exceed return total$/i, "مبلغ دریافت نمی‌تواند بیشتر از جمع برگشتی باشد."],
  [/^Discount cannot be greater than subtotal$/i, "تخفیف نمی‌تواند بیشتر از جمع اقلام باشد."],
  [/^Paid amount cannot be greater than total$/i, "مبلغ پرداختی نمی‌تواند بیشتر از مبلغ کل باشد."],
  [/^Payment amount cannot be greater than remaining .+$/i, "مبلغ پرداختی نمی‌تواند بیشتر از مبلغ باقی‌مانده باشد."],
  [/^Purchase has returns\. Cancel the return workflow manually instead\.?$/i, "این خرید برگشتی دارد؛ ابتدا روند برگشتی را به‌صورت دستی ابطال کنید."],
  [/^Sale has returns\. Cancel the return workflow manually instead\.?$/i, "این فروش برگشتی دارد؛ ابتدا روند برگشتی را به‌صورت دستی ابطال کنید."],
  [/^Purchase cannot be cancelled because its stock was already used or transferred$/i, "این خرید قابل ابطال نیست؛ موجودی آن مصرف یا انتقال شده است."],
  [/^Returned stock was already used and cannot be cancelled$/i, "این برگشتی قابل ابطال نیست؛ موجودی برگشته‌شده مصرف شده است."],
  [/^Stock movement has no lot to reverse$/i, "برای معکوس‌سازی این حرکت، لات موجودی پیدا نشد."],
  [/^Transfer movement has no lot to reverse$/i, "برای معکوس‌سازی انتقال، لات موجودی پیدا نشد."],
  [/^Cancellation movement cannot be cancelled again$/i, "حرکت ابطال‌شده دوباره قابل ابطال نیست."],
  [/^Stock movement is already cancelled$/i, "این حرکت موجودی قبلاً ابطال شده است."],
  [/^Sale request ID could not be verified$/i, "شناسه درخواست فروش معتبر نیست."],
  [/^This sale request ID belongs to another user$/i, "این شناسه فروش به کاربر دیگری تعلق دارد."],
  [/^Sale was committed but could not be reloaded$/i, "فروش ثبت شد، اما خواندن دوباره آن ناکام شد."],
  [/^Cancelled sale could not be reloaded$/i, "فروش ابطال شد، اما خواندن دوباره آن ناکام شد."],
  [/^Invalid COGS quality date range$/i, "بازه تاریخ گزارش قیمت تمام‌شده معتبر نیست."],
  [/^Explicit confirmation is required to repair this sale COGS$/i, "برای اصلاح قیمت تمام‌شده این فروش، تأیید صریح ضروری است."],
  [/^COGS cannot be repaired for a cancelled sale$/i, "قیمت تمام‌شده فروش ابطال‌شده قابل اصلاح نیست."],
  [/^COGS journal already exists for this sale$/i, "سند قیمت تمام‌شده این فروش قبلاً ثبت شده است."],
  [/^Journal already exists for this .+$/i, "سند حسابداری این معامله قبلاً ثبت شده است."],
  [/^(Subtotal|Purchase total|Expense amount|Receipt amount|Payment amount) must be greater than zero$/i, "مبلغ باید بیشتر از صفر باشد."],
  [/^Journal entry is not balanced\..*$/i, "سند حسابداری متوازن نیست؛ بدهکار و بستانکار باید برابر باشند."],
  [/^A journal line cannot have both debit and credit$/i, "یک سطر حسابداری نمی‌تواند هم‌زمان بدهکار و بستانکار باشد."],
  [/^Financial category type does not match entry kind$/i, "نوع کتگوری مالی با نوع سند یکسان نیست."],
  [/^Period has no workdays$/i, "این دوره حاضری روز کاری ندارد."],
  [/^Cancel payroll payments before cancelling the payroll run$/i, "پیش از ابطال دوره معاش، پرداخت‌های معاش را ابطال کنید."],
  [/^Payroll run cannot be marked paid while remaining amount exists$/i, "تا زمانی که مبلغ باقی‌مانده وجود دارد، دوره معاش قابل پرداخت کامل نیست."],
  [/^Close the attendance period before marking payroll as paid$/i, "پیش از ثبت پرداخت معاش، دوره حاضری را ببندید."],
  [/^Employee payment cancelled$/i, "پرداخت معاش ابطال شد."],
  [/^Payroll run cancelled$/i, "دوره معاش ابطال شد."],
  [/^Backup directory must be an absolute path$/i, "مسیر پوشه بکاپ باید کامل و معتبر باشد."],
  [/^Backup restore failed, and the safety backup was restored:.*$/i, "بازگردانی بکاپ ناکام شد، اما بکاپ ایمنی با موفقیت برگردانده شد."],
  [/^CRITICAL: backup restore and automatic rollback both failed\..*$/i, "بازگردانی بکاپ و بازگشت خودکار هر دو ناکام شدند. با مدیر سیستم تماس بگیرید."],
  [/^type must be logo, header or footer$/i, "نوع تصویر باید لوگو، سربرگ یا پابرگ باشد."],
  [/^Could not generate a unique product barcode$/i, "ساخت بارکود یکتای محصول ممکن نشد. دوباره کوشش کنید."],
  [/^Product is out of stock$/i, "موجودی این محصول تمام شده است."],
  [/^Product stock is lower than minimum stock$/i, "موجودی این محصول از حداقل تعیین‌شده کمتر است."],
  [/^Product lot is expired$/i, "تاریخ انقضای این لات گذشته است."],
  [/^Product lot will expire within \d+ days$/i, "تاریخ انقضای این لات نزدیک است."],
  [/^Resource sampling failed$/i, "خواندن وضعیت منابع سرور ناکام شد."],
  [/^sessionId is required$/i, "شناسه نشست صندوق فروش ضروری است."],
  [/^No session$/i, "نشست فعال پیدا نشد."],
  [/^Accounts failed$/i, "خواندن حساب‌ها ناکام شد."],
  [/^Parties failed$/i, "خواندن طرف‌حساب‌ها ناکام شد."],
  [/^Failed to load ledger$/i, "خواندن دفتر کل ناکام شد."],
  [/^Failed to prepare print$/i, "آماده‌سازی چاپ ناکام شد."],
  [/^Session expired$/i, "نشست شما منقضی شده است. دوباره وارد شوید."],
  [/^Product lookup integration tests require.*$/i, "عملیات انجام نشد."],
  [/^.+$/i, "عملیات انجام نشد. لطفاً دوباره کوشش کنید."]
];

/** Never expose raw internal or English error text to a customer. */
export function customerMessage(message: unknown): string {
  const value = typeof message === "string" ? message.trim() : "";
  if (!value) return "عملیات انجام نشد. لطفاً دوباره کوشش کنید.";
  if (exactMessages[value]) return exactMessages[value];

  // Existing Dari/Persian messages are already safe and intentionally specific.
  if (/[\u0600-\u06FF]/.test(value)) return value;

  for (const [pattern, replacement] of patterns) {
    const match = value.match(pattern);
    if (match) return typeof replacement === "function" ? replacement(match) : replacement;
  }

  return "عملیات انجام نشد. لطفاً دوباره کوشش کنید.";
}
